database:
  host: 127.0.0.1
  port: 3306
  user: mc
  password: 114514
  database: mc

hikari:
  maximum-pool-size: 20        # 最大连接数
  minimum-idle: 5              # 最小空闲连接数
  connection-timeout: 30000    # 连接超时（毫秒）
  idle-timeout: 600000         # 空闲超时（毫秒）
  max-lifetime: 1800000        # 连接最大生命周期（毫秒）